### ISSUE TITLE
Use environment file for Conda instead of pip

### ISSUE THREAD

**Issue by metal3d** [deepfakes/faceswap#1278]
**Is your feature request related to a problem? Please describe.**
Creating a conda environment then install tensorflow via "pip" requires to have CUDA and CuDnn libs on the system. That's a bit complex for some distributions. Conda proposes package for CUDA and Cuddn (and Tensoflow-gpu depends of them) 

So using a conda environment file will install Cuda package and Cudnn + tensorflow. That's way easier to install with only one simple command.

**Describe the solution you'd like**
Here is an environment.yml file that I did (using export with "history install", so Conda proposes packages that installs others dependencies, for example, no need to install "tk" while some packages are dependents):

```yaml
name: face-swap
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib[version='>=3.5.1']
  - pillow[version='>=9.2.0']
  - scikit-learn[version='>=1.1.0']
  - opencv[version='>=4.6.0.0']
  - ffmpy[version='>=0.3.0']
  - tqdm[version='>=4.64']
  - imageio[version='>=2.19.3']
  - numexpr[version='>=2.8.3']
  - typing-extensions[version='>=4.0.0']
  - tensorflow-probability[version='<0.17']
  - psutil[version='>=5.9.0']
  - imageio-ffmpeg[version='>=0.4.7']
  - fastcluster[version='>=1.2.6']
  - nvidia-ml-py[version='>=11.515,<300']
  - numpy[version='>=1.22.0']
  - tensorflow-gpu[version='>=2.7.0,<2.10.0']
```

It's then very easy to install with `conda create -f environment.yml` - the `face-swap` environment is created and requirements are installed.

NOTE: this is for Linux only here, with Nvidia dependencies.
