### ISSUE TITLE
Potential Issue in CI Workflow Affecting Code Coverage Accuracy

### ISSUE THREAD

**Issue by yunbolyu** [deepfakes/faceswap#1358]
Hello,

I'm working on collecting code coverage for this excellent project and have encountered a potential issue with the [CI workflow](https://github.com/deepfakes/faceswap/blob/master/.github/workflows/pytest.yml). Specifically, five jobs in GitHub Actions [conda(ubuntu-latest, nvidia); conda(ubuntu-latest, rocm); conda(macos-latest, nvidia); conda(windows-latest, nvidia); conda(windows-latest, directml)] do not execute simple and end-to-end tests. One job in GitHub Actions [conda(macos-latest, cpu)] does not execute end-to-end tests. This happened in your [recent GHA](https://github.com/deepfakes/faceswap/actions/runs/6633390593).
This seems to omit coverage for GPU-related or other code in /lib.

I've proposed a change in this commit: [GitHub Commit - d3da0fb](https://github.com/yunbolyu/faceswap/commit/d3da0fb4bfd0c2934e099ffe8698a978b8a93981) and generated a corresponding code coverage report here: [Code Coverage Report](https://app.codecov.io/gh/yunbolyu/faceswap/tree/master).

Could you please review this potential issue and confirm the change accurately reflects your repository's code coverage?

Thank you for your exceptional work on this project, and I apologize for any inconvenience my inquiries may cause.

Best,
Yunbo

**Comment by torzdf** [comment]
The jobs are explicitly excluded as per the notes in 

```yaml
# These backends will fail as GPU drivers not available
if: matrix.backend != 'rocm' && matrix.backend != 'nvidia' && matrix.backend != 'directml'
run: |
  FACESWAP_BACKEND="${{ matrix.backend }}" py.test -v tests/;
- name: End to End Tests
# These backends will fail as GPU drivers not available
# macOS fails on first extract test with 'died with <Signals.SIGSEGV: 11>'
if: matrix.backend != 'rocm' && matrix.backend != 'nvidia' && matrix.backend != 'directml' && matrix.os != 'macos-latest'        
```

If you are serious about improving the coverage of tests within the faceswap process, rather than just looking to shill another project, then we would very much welcome PRs that introduce more unit-tests, or look to resolve the above noted issues.

Please open a new issue/PR if you wish to contribute. This issue is closed as the problem disclosed is already known and documented.
